### ISSUE TITLE
feedback from SRI on predicate-remap.yaml

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1063]
From Richard Bruskiewich on 9/11/2020:
```
BFO:0000050:
  rename:
  - part_of
  - biolink:part_of
BFO:0000051:
  invert:
  - part_of
  # there is now actually a "biolink:has_part" term for the inverse of "biolink:part_of"
  - biolink:part_of
BFO:0000054:
  rename:
  - related_to
  - biolink:related_to
BFO:0000055:
  # See https://www.ebi.ac.uk/ols/ontologies/omiabis/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000055
  # Maybe biolink needs a new term 'realizes'. that said, there is actually a "biolink:has_part" term for the inverse of "biolink:part_of"
  invert:
  - part_of
  - biolink:part_of
BFO:0000056:
  # Can't find this term in the OLS but will use the RTX mapping for now(?)
  rename:
  - participates_in
  - biolink:participates_in
BFO:0000062:
  # exact inverse term is now biolink:preceded_by"
  invert:
  - precedes
  - biolink:precedes
```
