### ISSUE TITLE
long-term goal to remove RTXKG1 source predicate from edges

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1125]
The `rtx_kg1_neo4j_to_kg_json.py` script assigns the CURIE prefix `RTXKG1:` to `relation` properties for edges. Of course, most of the edge types in KG1 actually have source prefixes. We should probably find a way to get rid of the `RTXKG1` CURIE prefix and instead use the original source relations (with the original source CURIE prefix) in the `relation` edge property, where possible. This relates to a Slack post from Richard B. on Nov. 12,

> Hi  @ramseyst,  I’m tying up some loose ends in the  Biolink model prefixes.  Is RTXKG1: ‘http://kg1endpoint.rtx.ai/’ a reasonable mapping (I don’t think that the CURIES need to be resolvable, although that would be nice). Generally find  these among the predicates  which  you  had me map  into the model, e.g. RTXKG1:functionally_related_to

to which I responded:

> Hi Richard, I think that CURIE prefix will be gone from RTX KG2 (i.e., it will not appear as the original-source relation for any of our KG edges), within a few months. We are in the process of deprecating it. But yes, for the time being, that is a reasonable prefix-to-baseurl mapping.

Fixing this issue may require modifying `rtx_kg1_neo4j_to_kg_json.py` to create a literal dictionary whose keys are a combination of (1) the KG1 `provided_by` edge property and (2) the KG1 `relation` edge property, and whose values are what the source relations *should* be. That may be kind of a pain, as there are 102 combinations:
```
r.relation | r.provided_by
-- | --
"involved_in" | "gene_ontology"
"capable_of" | "gene_ontology"
"expressed_in" | "gene_ontology"
"expressed_in" | "BioLink"
"physically_interacts_with" | "PC2"
"physically_interacts_with" | "KEGG;UniProtKB"
"gene_mutations_contribute_to" | "OMIM"
"regulates_activity_of" | "PC2"
"gene_associated_with_condition" | "DisGeNet"
"physically_interacts_with" | "reactome"
"participates_in" | "reactome"
"has_phenotype" | "BioLink"
"associated_with_disease" | "BioLink"
"regulates_expression_of" | "PC2"
"targets" | "ChEMBL"
"targets" | "Pharos"
"cofactor" | "DGIdb;TTD"
"subclass_of" | "gene_ontology"
"affects" | "DGIdb;NCI"
"antagonist" | "DGIdb;ChemblInteractions"
"activator" | "DGIdb;GuideToPharmacologyInteractions"
"agonist" | "DGIdb;GuideToPharmacologyInteractions"
"inhibitor" | "DGIdb;GuideToPharmacologyInteractions"
"antagonist" | "DGIdb;GuideToPharmacologyInteractions"
"inhibitor" | "DGIdb;TTD"
"agonist" | "DGIdb;ChemblInteractions"
"antibody" | "DGIdb;GuideToPharmacologyInteractions"
"inhibitor" | "DGIdb;ChemblInteractions"
"agonist" | "DGIdb;TTD"
"affects" | "DGIdb;TEND"
"affects" | "DGIdb;TdgClinicalTrial"
"affects" | "DGIdb;CIViC"
"allosteric_modulator" | "DGIdb;GuideToPharmacologyInteractions"
"antagonist" | "DGIdb;TTD"
"antibody" | "DGIdb;TTD"
"affects" | "DGIdb;ChemblInteractions"
"affects" | "DGIdb;CKB"
"blocker" | "DGIdb;ChemblInteractions"
"positive_allosteric_modulator" | "DGIdb;ChemblInteractions"
"activator" | "DGIdb;ChemblInteractions"
"inhibitor" | "DGIdb;MyCancerGenome"
"modulator" | "DGIdb;TTD"
"affects" | "DGIdb;GuideToPharmacologyInteractions"
"affects" | "DGIdb;FDA"
"binder" | "DGIdb;TTD"
"inhibitor" | "DGIdb;TALC"
"affects" | "DGIdb;OncoKB"
"channel_blocker" | "DGIdb;GuideToPharmacologyInteractions"
"affects" | "DGIdb;ClearityFoundationClinicalTrial"
"affects" | "DGIdb;CGI"
"partial_agonist" | "DGIdb;ChemblInteractions"
"antisense" | "DGIdb;TTD"
"antibody" | "DGIdb;TALC"
"affects" | "DGIdb;ClearityFoundationBiomarkers"
"antisense_oligonucleotide" | "DGIdb;TALC"
"inverse_agonist" | "DGIdb;ChemblInteractions"
"stimulator" | "DGIdb;TTD"
"causes_or_contributes_to" | "SIDER"
"inhibitor" | "DGIdb;CancerCommons"
"affects" | "DGIdb;DoCM"
"indicated_for" | "MyChem.info"
"contraindicated_for" | "MyChem.info"
"activator" | "DGIdb;TTD"
"inhibitor" | "DGIdb;MyCancerGenomeClinicalTrial"
"blocker" | "DGIdb;TTD"
"modulator" | "DGIdb;ChemblInteractions"
"modulator" | "DGIdb;TALC"
"negative_modulator" | "DGIdb;ChemblInteractions"
"gating_inhibitor" | "DGIdb;GuideToPharmacologyInteractions"
"antibody" | "DGIdb;MyCancerGenome"
"antagonist" | "DGIdb;TALC"
"activator" | "DGIdb;TALC"
"affects" | "DGIdb;TTD"
"agonist" | "DGIdb;TALC"
"vaccine" | "DGIdb;TALC"
"inducer" | "DGIdb;TTD"
"antibody" | "DGIdb;CancerCommons"
"inducer" | "DGIdb;TALC"
"affects" | "DGIdb;MyCancerGenome"
"subclass_of" | "Monarch_SciGraph"
"affects" | "BioLink"
"regulates_expression_of" | "miRGate"
"subclass_of" | "DiseaseOntology"
"disease_caused_by_disruption_of" | "Monarch_SciGraph"
"realized_in_response_to" | "Monarch_SciGraph"
"disease_has_basis_in_dysfunction_of" | "Monarch_SciGraph"
"disease_causes_disruption_of" | "Monarch_SciGraph"
"disease_has_location" | "Monarch_SciGraph"
"realized_in_response_to_stimulus" | "Monarch_SciGraph"
"capable_of" | "Monarch_SciGraph"
"has_part" | "Monarch_SciGraph"
"lacks_part" | "Monarch_SciGraph"
"capable_of_part_of" | "Monarch_SciGraph"
"functionally_related_to" | "Monarch_SciGraph"
"contains_process" | "Monarch_SciGraph"
"has_completed" | "Monarch_SciGraph"
"output_of" | "Monarch_SciGraph"
"composed_primarily_of" | "Monarch_SciGraph"
"subClassOf" | "Monarch_SciGraph"
"equivalentClass" | "Monarch_SciGraph"
"site_of" | "Monarch_SciGraph"
"has_plasma_membrane_part" | "Monarch_SciGraph"
```
But... it's not so bad, because many of the upstream sources in KG1 are already directly ETL'd into KG2 (i.e., not via KG1) -- including Gene Ontology, ChEMBL, and DGIdb (the latter accounts for a lot of the combinations). For KG1 edges from *those* sources, we actually shouldn't need to bring the KG1 edge into KG2 at all, so we can just drop it. So perhaps the mapping dictionary needs to only have about 40 entries. 

[Long term, the goal is to eliminate the need to ETL KG1 altogether, in the KG2 build process, by making sure that we are already getting most of the knowledge direct from the upstream sources. Probably the major stumbling blocks at this point are PC2 and Reactome. But I view this long-term step as beyond the scope of this specific issue.]

**Comment by saramsey** [comment]
Richard B. adds:

> Once  your issue  1125 is  resolved,  please make a note of fixing (removing?) the  RTXKG1 mapping from  the  Biolink Model YAML  file.

**Comment by saramsey** [comment]
What from KG1 is still missing in KG2?

- microRNAs (tagging @kvarforl)
- protein-protein interactions (could get these from STRING or Reactome, whichever has easy-to-obtain PMIDs on the edges)
- protein-to-pathway associations (could get these from Reactome maybe?)
- maybe DisGeNet?

**Comment by ericawood** [comment]
> protein-protein interactions (could get these from STRING or Reactome, whichever has easy-to-obtain PMIDs on the edges)
> protein-to-pathway associations (could get these from Reactome maybe?)

Reactome has both of these. My initial ETL has the protein-to-pathway associations (which are now multi-hop -- pathway->reaction->protein) and I will work on bringing in the protein-protein interactions (which come in a TSV dump). I'm tagging #636 for documentation's sake.

**Comment by edeutsch** [comment]
I'm thinking that IntAct is the ultimate source for protein-protein interactions?
And Reactome for protein-pathway associations

**Comment by ericawood** [comment]
> I'm thinking that IntAct is the ultimate source for protein-protein interactions?

It looks fairly simple to ETL IntAct (it's a TSV file). Is this something that you would like @saramsey?

**Comment by edeutsch** [comment]
How large is it? I assume we just want the human protein interactions? Or? It's probably has many species. Do they also have human-other interactions?

**Comment by ericawood** [comment]
The whole thing is 4.6GB, but you are correct that that contains many species. There are species specific downloads available (as XML files), but the downsides of using those is that it would be more challenging to expand the data we process if we want more species down the road.

**Comment by edeutsch** [comment]
Are the species listed in the TSV file? or just identifiers from which species would need to be inferred?

**Comment by ericawood** [comment]
The species are listed in the TSV file.

Ex:


Taxid interactor A | Taxid interactor B
-- | --
taxid:9606(human)\|taxid:9606(Homo sapiens) | taxid:9606(human)\|taxid:9606(Homo sapiens)
taxid:-2(chemical synthesis)\|taxid:-2("Chemical synthesis (Chemical synthesis)") | taxid:9606(human)\|taxid:9606(Homo sapiens)
taxid:10141(cavpo)\|taxid:10141("Cavia porcellus (Guinea pig)") | taxid:9606(human)\|taxid:9606(Homo sapiens)

**Comment by edeutsch** [comment]
Sorry I'm so full of questions.. But it's fun to get answers so fast!
How many human-human interactions?
How many interactions where one end is human?

**Comment by ericawood** [comment]
Here are the counts from intact.txt (the 4.6GB file): (this does not include 3.7M intact_negative.txt)
Human-Human Interactions in IntAct: 587215
Interactions Where One End is Human: 104146

**Comment by ericawood** [comment]
Here are the counts from intact_negative.txt (the 3.7M file):
Human-Human Interactions in IntAct: 891
Interactions Where One End is Human: 32

**Comment by edeutsch** [comment]
Are we guessing that "negative" means "is known NOT to interact with"?

**Comment by ericawood** [comment]
>Are we guessing that "negative" means "is known NOT to interact with"?

Example annotations from the "negative" file suggests that that means "is known NOT to interact with":

- negative:The interaction does not occur under these experimental condition\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis
- negative:The interaction does not occur under these experimental condition\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis
- negative:The interaction does not occur under these experimental condition\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis
- comment:PAK1 interacts with the caspase cleaved form of p110PITSLRE, p110C, but not full length p110 PITSLRE or p58PITSLRE\|negative:\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis
- comment:PAK1 interacts with the caspase cleaved form of p110PITSLRE, p110C, but not full length p110 PITSLRE or p58PITSLRE\|negative:\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis
- negative:the interactions are not observed under these experimental conditions\|comment:domino\|comment:mint\|negative:true\|partial coverage:partial coverage
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F3B\|comment:homomint\|comment:domino\|comment:mint\|negative:true
- negative:the interactions are not observed under these experimental conditions\|comment:SUV39H1 interacts with the molecular surface formed by dimerization of the chromo shadow domain of mHP1small alpha\|comment:homomint\|comment:domino\|comment:mint\|negative:true
- comment:Cdc42 is GMPNP-bound\|negative:This experiment relates to a negative interaction
- negative:This interaction does not occur under these experimental conditions.\|comment:ST7 was V5/His tagged and ACTN2 was HA tagged.\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis\|dataset:Synapse - Interactions of proteins with an established role in the presynapse.
- negative:This interaction does not occur under these experimental conditions.\|comment:ST7 was V5/His tagged and TTID was HA tagged.\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis\|dataset:Synapse - Interactions of proteins with an established role in the presynapse.
- negative:This interaction does not occur under these experimental conditions.\|comment:ST7 was V5/His tagged and SNAP25BP was HA tagged.\|dataset:Apoptosis - Interactions involving proteins with a function related to apoptosis\|dataset:Synapse - Interactions of proteins with an established role in the presynapse.
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:ST3\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:ST3\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:ST3\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:F1\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:ST3\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|figure legend:ST3\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true\|dataset:Virus - Publications including interactions involving viral proteins
- negative:the interactions are not observed under these experimental conditions\|comment:mint\|negative:true\|partial coverage:partial coverage
- negative:the interactions are not observed under these experimental conditions\|comment:The article mentions that in similar co-precipitation exp, interaction between these two proteins was actually found.\|comment:mint\|negative:true\|partial coverage:partial coverage
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true
- negative:the interactions are not observed under these experimental conditions\|comment:mint\|negative:true
- negative:the interactions are not observed under these experimental conditions\|comment:homomint\|comment:mint\|negative:true

**Comment by saramsey** [comment]
> > I'm thinking that IntAct is the ultimate source for protein-protein interactions?
> 
> It looks fairly simple to ETL IntAct (it's a TSV file). Is this something that you would like @saramsey?

Good question. I guess the first thing I would do is try to assess it in terms of our KG2 knowledge source inclusion criteria,
https://github.com/RTXteam/RTX/tree/master/code/kg2#what-criteria-do-you-use-to-select-sources-to-include-in-kg2

<img width="885" alt="Screen Shot 2021-03-16 at 6 34 22 PM" src="https://user-images.githubusercontent.com/5562107/111401298-3f429580-8686-11eb-82ad-679bece364ee.png">

I think we should consider using the PC2 flat files for ETL:
https://www.pathwaycommons.org/archives/PC2/v12/

For example, we could easily do an ETL of the KEGG pathway to UniProtKB protein associations 
https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.All.uniprot.gmt.gz

We could also ETL all PPI interactions (with PubMed IDs, and including IntAct):
https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.All.hgnc.txt.gz

**Comment by ericawood** [comment]
This hasn't been updated in a while, but we decided to ETL IntAct because it is still being updated and Pathway Commons is not. I have attempted to map the IntAct predicates to biolink predicates and would appreciate feedback. They are all PSI-MI interactions and I used https://www.ebi.ac.uk/ols/ontologies/mi in my effort to map them.

```
MI:0192: # acetylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0194: # cleavage reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0195: # covalent bonding
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0197: # deacetylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0203: # dephosphorylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0204: # deubiquitination reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0210: # hydroxylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0211: # lipid addition
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0212: # lipoprotein cleavage reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0213: # methylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0214: # myristoylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0216: # palmitoylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0217: # phosphorylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0220: # ubiquitination reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0403: # colocalization
  rename:
  - colocalizes_with
  - biolink:colocalizes_with
MI:0407: # direct interaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0408: # disulfide bond
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0414: # enzymatic reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0556: # transglutamination reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0557: # adp_ribosylation_reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0559: # glycosylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0566: # sumoylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0567: # neddylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0569: # deneddylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0570: # protein cleavage
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0572: # dna cleavage
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0844: # phosphotransfer reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0871: # demethylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0882: # atpase reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0883: # gtpase reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0902: # rna reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:0914: # association
  rename:
  - interacts_with
  - biolink:interacts_with
MI:0915: # physical associaiton
  rename:
  - physically_interacts_with
  - biolink:physically_interacts_with
MI:0945: # oxidoreductase activity electron transfer reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:1126: # self interaction
  rename:
  - interacts_with
  - biolink:interacts_with
MI:1127: # putative self interaction
  rename:
  - interacts_with
  - biolink:interacts_with
MI:1148: # ampylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:1237: # proline isomerization reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:1310: # de-ADP-ribosylation reaction
  rename:
  - directly_interacts_with
  - biolink:directly_interacts_with
MI:2364: # proximity
  rename:
  - colocalizes_with
  - biolink:colocalizes_with
```
