### ISSUE TITLE
For drug->disease queries, expand on KG2 + use the DTD model

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1294]
This may be the next "standup meeting" test case. Would be nice to include predictions as well as known treatments. Will need to modify [this yaml file](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml).

**Comment by edeutsch** [comment]
The current paradigm is that if the query specifies "treats", then we just do a straight KG/KB lookup, i.e. "known to treat". If instead the query specifies something more generic like "associated with", then we fire up DTD and more info:

```
one_hop_drug_treats_disease:
    name: one hop with start node drug, end node disease
    description: Two nodes, start has a specific curie, end node has category specified as biolink:ChemicalSubstance (or drug?!)
    restated_question: What n01(category)s is known to treat n00(name)?
    template:
      - n00(id,category=biolink:Disease)
      - e00(predicate=treats)
      - n01(category=biolink:ChemicalSubstance)
    DSL:
      - expand(kp=ARAX/KG2)
      - overlay(action=compute_ngd, subject_qnode_key=n00, object_qnode_key=n01, virtual_relation_label=N1)
      - resultify()
      - filter_results(action=limit_number_of_results, max_results=50)

  one_hop_drug_somehow_related_to_disease:
    name: one hop with start node drug, end node disease
    description: Two nodes, start has a specific curie, end node has category specified as biolink:ChemicalSubstance (or drug?!)
    restated_question: What n01(category)s may treat n00(name)?
    template:
      - n00(id,category=biolink:Disease)
      - e00()
      - n01(category=biolink:ChemicalSubstance)
    DSL:
      - expand(kp=ARAX/KG2, continue_if_no_results=true)
      - expand(kp=BTE, continue_if_no_results=true)
      - overlay(action=overlay_clinical_info, observed_expected_ratio=true, subject_qnode_key=n00, object_qnode_key=n01, virtual_relation_label=CP1)
      - overlay(action=predict_drug_treats_disease, subject_qnode_key=n01, object_qnode_key=n00, virtual_relation_label=P1)
      - filter_kg(action=remove_edges_by_attribute, edge_attribute=probability_treats, direction=below, threshold=0.75, remove_connected_nodes=true, qnode_key=n01)
      - overlay(action=compute_ngd, subject_qnode_key=n00, object_qnode_key=n01, virtual_relation_label=N1)
      - resultify(ignore_edge_direction=true)
      - filter_results(action=limit_number_of_results, max_results=50)
```
