### ISSUE TITLE
Add a cached version of SRI info or find another way of speeding up dtd tests

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1554]
See here: https://travis-ci.com/github/RTXteam/RTX/builds/231574952

Seem to have a bunch of these before failure:
```
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
WARNING: returned with status 404 while retrieving ancestors for biolink:ChemicalSubstance
```

Then the following traceback:

```
Response:

  status: ERROR

  n_errors: 1  n_warnings: 0  n_messages: 58

  error_code: UncaughtARAXiError   message: An uncaught error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')): ['Traceback (most recent call last):\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen\n    chunked=chunked,\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 1344, in getresponse\n    response.begin()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 306, in begin\n    version, status, reason = self._read_status()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 275, in _read_status\n    raise RemoteDisconnected("Remote end closed connection without"\n', 'http.client.RemoteDisconnected: Remote end closed connection without response\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/adapters.py", line 449, in send\n    timeout=timeout\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/util/retry.py", line 410, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise\n    raise value.with_traceback(tb)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen\n    chunked=chunked,\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 1344, in getresponse\n    response.begin()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 306, in begin\n    version, status, reason = self._read_status()\n', '  File "/opt/python/3.7.6/lib/python3.7/http/client.py", line 275, in _read_status\n    raise RemoteDisconnected("Remote end closed connection without"\n', "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 533, in execute_processing_plan\n    overlay.apply(response, action[\'parameters\'])\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/test/../ARAXQuery/ARAX_overlay.py", line 531, in apply\n    \'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/test/../ARAXQuery/ARAX_overlay.py", line 847, in __predict_drug_treats_disease\n    response = PDTD.predict_drug_treats_disease()\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/test/../ARAXQuery/Overlay/predict_drug_treats_disease.py", line 196, in predict_drug_treats_disease\n    converted_target_curie = self.convert_to_trained_curies(target_curie)\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/test/../ARAXQuery/Overlay/predict_drug_treats_disease.py", line 139, in convert_to_trained_curies\n    normalizer_result = self.synonymizer.get_canonical_curies(curies=[input_curie], return_all_categories=True)\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/node_synonymizer.py", line 1963, in get_canonical_curies\n    results[entity][\'expanded_categories\'] = category_manager.get_expansive_categories(row[4])\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/category_manager.py", line 133, in get_expansive_categories\n    ancestors = self.get_ancestors(category)\n', '  File "/home/travis/build/RTXteam/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/category_manager.py", line 86, in get_ancestors\n    response_content = requests.get(url, headers={\'accept\': \'application/json\'})\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/api.py", line 76, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/api.py", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests_cache/core.py", line 136, in request\n    **kwargs\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/sessions.py", line 530, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests_cache/core.py", line 109, in send\n    return send_request_and_cache_response()\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests_cache/core.py", line 97, in send_request_and_cache_response\n    response = super(CachedSession, self).send(request, **kwargs)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/sessions.py", line 643, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/adapters.py", line 498, in send\n    raise ConnectionError(err, request=request)\n', "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n"]
```
